# Generated by Django 4.0.3 on 2022-04-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
