# Generated by Django 4.0.3 on 2022-04-15 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostfound', '0004_category_item_person_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='found_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='found', to=settings.AUTH_USER_MODEL),
        ),
    ]
