# Generated by Django 4.0.3 on 2022-04-15 18:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0006_alter_item_found_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='found_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='lost_by',
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='person_first_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='person_last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='roll_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='room_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
