# Generated by Django 4.0.3 on 2022-04-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0007_remove_item_found_by_remove_item_lost_by_item_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
