# Generated by Django 4.0.3 on 2022-04-15 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0008_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_first_name', models.CharField(default='a', max_length=100)),
                ('person_last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@example.com', max_length=100)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('roll_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(10)])),
                ('room_number', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(10)])),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lostfound.category')),
            ],
        ),
    ]
