# Generated by Django 4.0.3 on 2022-04-15 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0009_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
