# Generated by Django 4.0.3 on 2022-04-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0012_item_hotel_main_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='person_first_name',
            field=models.CharField(max_length=100),
        ),
    ]
