# Generated by Django 4.0.3 on 2022-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0013_alter_item_email_alter_item_person_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
