# Generated by Django 4.0.3 on 2022-04-16 08:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lostfound', '0014_remove_item_hotel_main_img_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lost_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lost', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='roll_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='room_number',
            field=models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
