# Generated by Django 4.0.3 on 2022-04-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostfound', '0015_item_lost_by_alter_item_roll_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lost_by',
        ),
    ]
